version: '3'

services:
  db:
    image: postgres:9.6-alpine
    volumes:
      - ./docker/volumes/postgres:/var/lib/postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'
    networks:
      - web
  # pgadmin:
  #   image: dpage/pgadmin4
  #   volumes:
  #     - ./docker/volumes/pgadmin:/var/lib/pgadmin
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
  #   ports:
  #     - '5050:80'
  #   networks:
  #     - web

networks:
  web:
    driver: bridge
